# Generated by Django 3.0.8 on 2020-07-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200722_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(help_text='项目名称', max_length=200, unique=True, verbose_name='项目名称'),
        ),
    ]
