# Generated by Django 3.0.8 on 2020-07-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200722_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='desc',
            field=models.TextField(blank=True, default='xxx简介', help_text='项目简介', verbose_name='项目简介'),
        ),
    ]
